/* A44 - AUTORELACIONAMENTO */


CREATE TABLE CURSOS(
	IDCURSO INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30),
	HORAS INT,
	VALOR FLOAT(10,2),
	ID_PREREQ INT
);

ALTER TABLE CURSOS ADD CONSTRAINT FK_PREREQ
FOREIGN KEY(ID_PREREQ) REFERENCES CURSOS(IDCURSO);

INSERT INTO CURSOS VALUES(NULL,'BD RELACIONAL',20,400.00,NULL);
INSERT INTO CURSOS VALUES(NULL,'BUSINESS INTELLIGENCE',40,800.00,1);
INSERT INTO CURSOS VALUES(NULL,'RELATORIOS AVANCADOS',20,600.00,2);
INSERT INTO CURSOS VALUES(NULL,'LOGICA PROGRAM',20,400.00,NULL);
INSERT INTO CURSOS VALUES(NULL,'RUBY',30,500.00,4);

SELECT * FROM CURSOS;

SELECT NOME, VALOR, HORAS, IFNULL(ID_PREREQ,"SEM REQ") REQUISITO
FROM CURSOS;

/* NOME, VALOR, HORAS E O NOME DO PRE REQUISITO DO CURSO */

SELECT C.NOME, C.VALOR, C.HORAS,IFNULL(P.NOME,"--") AS REQUISITO
FROM CURSOS C
LEFT JOIN CURSOS P
ON C.IDCURSO = P.ID_PREREQ;

+-----------------------+--------+-------+-----------------------+
| NOME                  | VALOR  | HORAS | REQUISITO             |
+-----------------------+--------+-------+-----------------------+
| BD RELACIONAL         | 400.00 |    20 | BUSINESS INTELLIGENCE |
| BUSINESS INTELLIGENCE | 800.00 |    40 | RELATORIOS AVANCADOS  |
| RELATORIOS AVANCADOS  | 600.00 |    20 | --                    |
| LOGICA PROGRAM        | 400.00 |    20 | RUBY                  |
| RUBY                  | 500.00 |    30 | --                    |
+-----------------------+--------+-------+-----------------------+




