/* BLOCOS IF E ELSE */

DECLARE
	@NUMERO INT = 5
BEGIN 
	IF @NUMERO= 5
		PRINT ' O VALOR É VERDADEIRO'
	ELSE
		PRINT 'O VALOR É FALSO'
END
GO


CREATE PROCEDURE SOMA1 @VALOR INT
AS
begin
	IF @VALOR > 5
		PRINT 'VALOS REAL'
	ELSE
		PRINT ' VALOR FALSO'
end
go

EXEC SOMA1 @VALOR = 6
EXEC SOMA1 @VALOR = 10
EXEC SOMA1 @VALOR = 1
EXEC SOMA1 @VALOR = 3

/* CASE */

SELECT * FROM CARROS;
DECLARE 
	@CONTADOR INT
BEGIN
	SELECT 
	CASE 
		WHEN FABRICANTE = 'FIAT' THEN 'FAIXA 1'
		WHEN FABRICANTE = ' CHEVROLET' THEN 'FAIXA 2'
		ELSE ' OUTRAS FAIXAS'
	END AS "INFORMAÇÕES", *  FROM CARROS

END
GO

/*- BLOCO NOMEADO */
DROP PROCEDURE CONF_VALORES
go

CREATE PROCEDURE CONF_VALORES @VALORES int
AS
		IF @VALORES >= 0 and @VALORES <= 20
			PRINT 'VALOR entre 0 e 20 '
		IF @VALORES >= 21 and @VALORES <=50
			PRINT 'VALOR ENTRE 21 E 50'
		ELSE
			PRINT 'VALORES MAIOR DE 50'
GO
	
EXEC CONF_VALORES @VALORES = 21
EXEC CONF_VALORES @VALORES = 103
EXEC CONF_VALORES @VALORES = 4
EXEC CONF_VALORES @VALORES = 51