/* BLOCO DE EXECUÇÃO */

BEGIN 
	PRINT 'PRIMEIRO BLOCO LEGAL'
END
GO

/* BLOCOS DE ATRIBUIÇÃO DE VARIAVEIS */

DECLARE
	@contador varchar(50)
BEGIN
	set @contador = 'oie'
	print @contador
END
GO

DECLARE
	@contador varchar(50)
BEGIN
	set @contador = 'oie'
	print @contador
END
GO


DECLARE 
	
		@V_NUMERO NUMERIC(10,2) = 100.52,
		@V_DATA DATETIME = '20170207'
BEGIN 
		PRINT 'VALOR NUMERICO: ' + CAST(@V_NUMERO AS VARCHAR)
		PRINT 'VALOR NUMERICO: ' + CONVERT(VARCHAR,@V_NUMERO)
		PRINT 'VALOR DATA: ' + CAST(@V_DATA AS VARCHAR)
		PRINT 'VALOR DATA: ' +CONVERT(VARCHAR, @V_DATA,105)
		PRINT 'VALOR DATA: ' +CONVERT(VARCHAR, @V_DATA,120)
		PRINT 'VALOR DATA: ' +CONVERT(VARCHAR, @V_DATA,121)
END
GO


/* ATRIBUINDO RESULTADOS A UMA VARIAVEL */

CREATE TABLE CARROS(
	CARRO VARCHAR(20),
	FABRICANTE VARCHAR(30)
)
GO

INSERT INTO CARROS VALUES('KA','FORD')
INSERT INTO CARROS VALUES('FIESTA','FORD')
INSERT INTO CARROS VALUES('PRISMA','FORD')
INSERT INTO CARROS VALUES('CLIO','RENAULT')
INSERT INTO CARROS VALUES('SANDERO','RENAULT')
INSERT INTO CARROS VALUES('CHEVETE','CHEVROLET')
INSERT INTO CARROS VALUES('OMEGA','CHEVROLET')
INSERT INTO CARROS VALUES('PALIO','FIAT')
INSERT INTO CARROS VALUES('DOBLO','FIAT')
INSERT INTO CARROS VALUES('UNO','FIAT')
INSERT INTO CARROS VALUES('GOL','VOLKSWAGEN')
GO

SELECT * FROM CARROS
GO


DECLARE

	@V_CONT_FORD INT,
	@V_CONT_FIAT INT
BEGIN
		-- METODO 1
	SET @V_CONT_FORD = (SELECT COUNT(*) FROM CARROS
	WHERE FABRICANTE= 'FORD')

	print 'QUANTIDADE FORD: ' +CAST(@V_CONT_FORD AS VARCHAR)

		-- METODO 2
	SELECT @V_CONT_FIAT = COUNT(*) FROM CARROS
	WHERE FABRICANTE = 'FIAT'

	PRINT 'QUANTIDADE FIAT: ' + CONVERT(VARCHAR, @V_CONT_FIAT)
END
GO

