
CREATE TABLE MAQUINAS(
	MAQUINA VARCHAR(50),
	DIA INT,
	QTDA NUMERIC(10,2));
	
/* IMPORTAR ARQUIVO */
C:\Users\Aninha\Desktop\curso_mysql
/* quando trabalhamos com postgreSQL precisamos colocar a pasta como publico se nao, nao conseguimos acessar*/

COPY MAQUINAS 
FROM 'C:\Users\Public\Arquivo\LogMaquinas.csv'
DELIMITER ','
CSV HEADER ;

SELECT * FROM MAQUINAS;


/* QUAL A MEDIA DAS MAQUINAS */

SELECT MAQUINA, AVG(QTDA) 
FROM MAQUINAS
GROUP BY MAQUINA
ORDER BY 2 DESC;

/* ARREDONDANDO CASAS DECIMAIS */

SELECT MAQUINA, ROUND(AVG(QTDA),2)
FROM MAQUINAS
GROUP BY MAQUINA
ORDER BY 2 DESC;

/* CALCULANDO A MODA */

SELECT MAQUINA, QTDA, COUNT(QTDA)
FROM MAQUINAS
WHERE MAQUINA = 'Maquina 01'
GROUP BY MAQUINA, QTDA;

/* CALCULANDO A MODA DE CADA MAQUINA */
/* QUAL A MODA DAS QUANTIDADES DE CADA MAQUINA */

SELECT MAQUINA, QTDA, COUNT(*) FROM MAQUINAS
WHERE MAQUINA = 'Maquina 01'
GROUP BY MAQUINA, QTDA
ORDER BY 3 DESC
LIMIT 1;

SELECT MAQUINA, QTDA, COUNT(*) FROM MAQUINAS
WHERE MAQUINA = 'Maquina 02'
GROUP BY MAQUINA, QTDA
ORDER BY 3 DESC
LIMIT 1;


SELECT MAQUINA, QTDA, COUNT(*) FROM MAQUINAS
WHERE MAQUINA = 'Maquina 03'
GROUP BY MAQUINA, QTDA
ORDER BY 3 DESC
LIMIT 1;

USE data_science;
/* MODA DO DATASET INTEIRO */

SELECT  qtda, COUNT(QTDA) AS MODA
FROM MAQUINAS
GROUP BY QTDA
ORDER BY COUNT(QTDA) DESC;



/* AMPLITUDE */

SELECT 	
		MAQUINA,
		MAX(QTDA) AS MAXIMO,
		MIN(QTDA) AS MINIMO,
		MAX(QTDA) - MIN(QTDA) AS AMPLITUDE,
		ROUND(AVG(QTDA),2) AS MEDIA
FROM MAQUINAS
GROUP BY MAQUINA;


/* DESVIO PADRÃO E VARIÂNCIA */

STDDEV_POP(COLUNA)
VAR_POP(COLUNA)

SELECT 	
		MAQUINA,
		MAX(QTDA) AS MAXIMO,
		MIN(QTDA) AS MINIMO,
		MAX(QTDA) - MIN(QTDA) AS AMPLITUDE,
		ROUND(AVG(QTDA),2) AS MEDIA,
		ROUND(STDDEV_POP(QTDA),2) AS DESV_PADRAO,
		ROUND(VAR_POP(QTDA),2) AS VARIANCIA
FROM MAQUINAS
GROUP BY MAQUINA;


/* MEDIANA */ 
CREATE OR REPLACE FUNCTION _final_median(NUMERIC[])
   RETURNS NUMERIC AS
$$
   SELECT AVG(val)
   FROM (
     SELECT val
     FROM unnest($1) val
     ORDER BY 1
     LIMIT  2 - MOD(array_upper($1, 1), 2)
     OFFSET CEIL(array_upper($1, 1) / 2.0) - 1
   ) sub;
$$
LANGUAGE 'sql' IMMUTABLE;


										 
CREATE AGGREGATE median(NUMERIC) (
  SFUNC=array_append,
  STYPE=NUMERIC[],
  FINALFUNC=_final_median,
  INITCOND='{}'
);
					
										 
SELECT ROUND(MEDIAN(QTDA),2) AS MEDIANA
FROM MAQUINAS;

SELECT ROUND(MEDIAN(QTDA),2) AS MEDIANA
FROM MAQUINAS
WHERE MAQUINA = 'Maquina 01';
								
SELECT MEDIAN(QTDA) AS MEDIANA
FROM MAQUINAS
WHERE MAQUINA = 'Maquina 02';
										 
SELECT MEDIAN(QTD) AS MEDIANA
FROM MAQUINAS
WHERE MAQUINA = 'Maquina 03';

SELECT MAQUINA, ROUND(MEDIAN(QTDA),2) AS MEDIANA
FROM MAQUINAS
GROUP BY MAQUINA;
										 

INSERT INTO MAQUINAS VALUES('Maquina 01',11,15.9);
INSERT INTO MAQUINAS VALUES('Maquina 02',11,15.4);
INSERT INTO MAQUINAS VALUES('Maquina 03',11,15.7);
INSERT INTO MAQUINAS VALUES('Maquina 01',12,30);
INSERT INTO MAQUINAS VALUES('Maquina 02',12,24);
INSERT INTO MAQUINAS VALUES('Maquina 03',12,45);
										 
delete from maquinas where dia = 11 or dia = 12;


