/* Modelagem simples(CONCEITUAL)
 ENTIDADE = TABELA 
CAMPOS = ATRIBUTOS */

CLIENTE 

NOME - CARACTER(100)
CPF - NUMERICO(11)
SEXO - CARACTER(1)
EMAIL - CARACTER(30)
ENDEREÇO - CARACTER(100)
TELEFONE - CARACTER(30)

/* Processos de Modelagem */

/* fase 01 e 02 - AD ADM DE DADOS */

Modelagem Conceitual - RASCUNHO		
Modelagem Logica - QUALQUER PROGRAMA DE MODELAGEM

/* FASE 03 - DBA  / AD */

Modelagem Física -  SCRIPTS DE BANCO


/* INICIANDO A MODELAGEM FÍSICA 
char = 
varchar = */


create database projeto;

USE projeto;

CREATE TABLE CLIENTE( 
	nome varchar(100), 
	sexo CHAR(1), 
	email varchar(30), 
	cpf int(11),
	telefone varchar (30),
	endereco varchar(100)

);

SHOW TABLES;

/* DESCRIÇÃO DOS CAMPOS */

DESC CLIENTE;

/* FORMA 01 - OMITINDO AS COLUNAS */

INSERT INTO CLIENTE VALUES('JOAO','M','JOAO@GMAIL.COM',988638273,'22923110','MAIA LACERDA - ESTACIO - RIO DE JANEIRO - RJ');

INSERT INTO CLIENTE VALUES('CELIA','F','CELIA@GMAIL.COM',541521456,'25078869','RIACHUELO - CENTRO - RIO DE JANEIRO - RJ');

INSERT INTO CLIENTE VALUES('JORGE','M',NULL,885755896,'58748895','OSCAR CURY - BOM RETIRO - PATOS DE MINAS - MG');

/* FORMA 02 - COLOCANDO AS COLUNAS */

INSERT INTO CLIENTE(NOME,SEXO,ENDERECO,TELEFONE,CPF) VALUES('LILIAN','F','SENADOR SOARES - TIJUCA - RIO DE JANEIRO - RJ','947785696',887774856);

/* FORMA 03 - INSERT COMPACTO - SOMENTE MYSQL */

INSERT INTO CLIENTE VALUES('ANA','F','ANA@GLOBO.COM',85548962,'548556985','PRES ANTONIO CARLOS - CENTRO - SAO PAULO - SP'),
                          ('CARLA','F','CARLA@TERATI.COM.BR',7745828,'66587458','SAMUEL SILVA - CENTRO - BELO HORIZONTE - MG');
						  
INSERT INTO CLIENTE(NOME,SEXO,ENDERECO,TELEFONE,CPF) VALUES('CLARA','F','SENADOR SOARES - TIJUCA - RIO DE JANEIRO - RJ','883665843',99999999999);

INSERT INTO CLIENTE(NOME,SEXO,ENDERECO,TELEFONE,CPF) VALUES('CLARA','F','SENADOR SOARES - TIJUCA - RIO DE JANEIRO - RJ','883665843',22222222222);


/* PROJEÇÃO */

SELECT NOW() AS "DATA_HORA", "ANINHA" AS "ESTUDANTE";

SELECT NOME, CPF, SEXO, TELEFONE FROM CLIENTE;

SELECT NOME, TELEFONE,SEXO, NOW() AS DATA FROM CLIENTE;

/* ALIAS DE COLUNAS */

SELECT NOME AS CLIENTE ,CPF, SEXO AS GENERO FROM CLIENTE;


/* FILTRANDO */

SELECT NOME, SEXO AS GENERO FROM CLIENTE 
WHERE SEXO = "F";

SELECT NOME, ENDERECO FROM CLIENTE
WHERE SEXO = 'F';

SELECT NOME, SEXO FROM CLIENTE
WHERE ENDERECO = 'RJ';

SELECT NOME, SEXO AS GENERO FROM CLIENTE
 WHERE SEXO = "F" 
 AND ENDERECO LIKE "%RJ";


/* EXERCICIO */

CREATE DATABASE LIVRARIA;

CREATE TABLE LIVROS(
		NOME_LIVRO VARCHAR(100),
		NOME_AUTOR VARCHAR(100),
		SEXO_AUTOR CHAR(1), 
		NUMERO_PAGINAS INT(100),
		NOME_EDITORA VARCHAR(100), 
		VALOR_LIVRO FLOAT(10,2),
		UF_LIVROS CHAR(2),
		ANO_PUBLICADO INT(4)

);

INSERT INTO LIVROS VALUES('Cavaleiro Real','Ana Claudia','F',465,'Atlas',49.9,'RJ',2009);
INSERT INTO LIVROS VALUES('SQL para leigos','João Nunes','M',450,'Addison',98,'SP',2018);
INSERT INTO LIVROS VALUES('Receitas Caseiras','Celia Tavares','F',210,'Atlas',45,'RJ',2008);
INSERT INTO LIVROS VALUES('Pessoas Efetivas','Eduardo Santos','M',390,'Beta',78,'RJ',2018);
INSERT INTO LIVROS VALUES('Habitos Saudáveis','Eduardo Santos','M',630,'Beta',150,'RJ',2019);
INSERT INTO LIVROS VALUES('A Casa Marrom','Hermes Macedo','M',250,'Bubba',60,'MG',2016);
INSERT INTO LIVROS VALUES('Estacio Querido','Geraldo Francisco','M',310,'Insignia',100,'ES',2015);
INSERT INTO LIVROS VALUES('Pra sempre amigas','Leda Silva','F',510,'Insignia',78,'ES',2011);
INSERT INTO LIVROS VALUES('Copas Inesqueciveis','Marco Alcantara','M',200,'Larson',130,'RS',2018);
INSERT INTO LIVROS VALUES('O poder da mente','Clara Mafra','F',120,'Continental',56,'SP',2017);


SELECT * FROM LIVROS;

SELECT NOME_LIVRO, NOME_EDITORA FROM LIVROS;

SELECT NOME_LIVRO, UF_LIVROS, SEXO_AUTOR FROM LIVROS
WHERE SEXO_AUTOR = "M";

SELECT NOME_LIVRO, VALOR_LIVRO, SEXO_AUTOR FROM LIVROS
WHERE SEXO_AUTOR = "F";

SELECT NOME_LIVRO, NUMERO_PAGINAS, SEXO_AUTOR FROM LIVROS
WHERE SEXO_AUTOR = "F";

SELECT NOME_LIVRO,VALOR_LIVRO, UF_LIVROS FROM LIVROS
WHERE UF_LIVROS = "SP";

SELECT * FROM LIVROS
WHERE SEXO_AUTOR = "M" 
AND UF_LIVROS ="SP" OR UF_LIVROS="RJ";

SELECT * FROM LIVROS
WHERE SEXO_AUTOR = "M" 
AND (UF_LIVROS="RJ" OR UF_LIVROS="SP");

/* AND = TODAS AS CONDIÇÕES TEM QUE SER VERDADEIRA
  OR = APENAS UMA CONDIÇÃO TEM QUE SER VERDADEIRA 
*/

SHOW DATABASES;

USE PROJETO;


 SELECT NOME, SEXO, ENDERECO FROM CLIENTE
 WHERE SEXO = "M" AND ENDERECO LIKE "%RJ";/* AS DUAS CONDIÇÕES TEM QUE SER VERDADE*/
 
 SELECT NOME,SEXO, ENDERECO FROM CLIENTE
 WHERE SEXO = "M" OR ENDERECO LIKE "%RJ";  /* APENAS UMA CONDIÇÃO TEM QUE SER VERDADE */
 
 SELECT COUNT(*) AS CONTAGEM_LINHAS FROM CLIENTE;
 
 SELECT SEXO, COUNT(*) FROM CLIENTE
 GROUP BY SEXO;
 
 SELECT NOME, SEXO, ENDERECO, COUNT(*) FROM CLIENTE
 WHERE SEXO = "F"
 OR ENDERECO ="%RJ";
 
 SELECT NOME, SEXO, ENDERECO, COUNT(*) FROM CLIENTE
 WHERE ENDERECO ="%RIO DE JANEIRO%"
 AND SEXO = "F";