CREATE TABLE LANCAMENTO_CONTABIL(
	CONTA INT,
	VALOR INT,
	DES_CRED CHAR(1)
)
GO

SELECT * FROM LANCAMENTO_CONTABIL;

/* IMPORTANDO ARQUIVO DENTRO DA MINHA TABELA
\t = TAB */


BULK INSERT LANCAMENTO_CONTABIL
FROM 'C:\Users\BlueShift\Desktop\Curso banco de dados\CONTAS.TXT'
WITH 
(	
	FIRSTROW = 2,
	DATAFILETYPE = 'char',
	FIELDTERMINATOR = '\t',
	ROWTERMINATOR ='\n'
)
GO

SELECT * FROM LANCAMENTO_CONTABIL;

/* desafio */

/* DESAFIO DO SALDO 
QUERY QUE TRAGA O NUMERO DA CONTA
SALDO - DEVEDOR OU CREDOR */

SELECT CONTA, VALOR, DES_CRED,
CHARINDEX('D',DES_CRED) AS DEBITO,
CHARINDEX('C',DES_CRED) AS CREDITO,
CHARINDEX('C',DES_CRED) * 2 - 1 AS MULTIPLICADOR
FROM LANCAMENTO_CONTABIL
GO

SELECT CONTA,
SUM(VALOR * (CHARINDEX('C',DES_CRED) * 2 - 1)) AS SALDO
FROM LANCAMENTO_CONTABIL
GROUP BY CONTA
GO