/* filtros em grupos VALORES NUMERICOS */

SELECT NOME, SALARIO 
FROM FUNCIONARIOS
WHERE SALARIO >110203;

/* FILTROS BASEADOS EM MULTIPLAS TIPOS E COLUNAS  EM RELACIONAMENTOS 1*1 SE TRATANDOD E UMA COLUNA SEMPRE DARA FALSO*/
SELECT DEPARTAMENTO FROM FUNCIONARIOS; 

SELECT NOME, SALARIO, DEPARTAMENTO
FROM FUNCIONARIOS
WHERE SALARIO > 110203
AND DEPARTAMENTO = 'Esportes';

SELECT NOME, SALARIO, DEPARTAMENTO
FROM FUNCIONARIOS
WHERE SALARIO > 110203
or DEPARTAMENTO = 'Esportes';

/* FILTROS BASEADOS EM CARACTERES E NUMERICOS */

SELECT SUM(SALARIO), DEPARTAMENTO
FROM FUNCIONARIOS
WHERE DEPARTAMENTO LIKE 'B%'
GROUP BY DEPARTAMENTO
HAVING SUM(SALARIO) > 4500000;

/* MULTIPLOS CONTADORES */

SELECT COUNT(*) AS QTDA,
	COUNT(sexo) FILTER(where (sexo ='Masculino')) as Masc,
	COUNT(SEXO) FILTER(WHERE(SEXO = 'Feminino')) as Fem,
	COUNT(DEPARTAMENTO) FILTER(WHERE (DEPARTAMENTO = 'Esporte')) as Dep_esportes
FROM FUNCIONARIOS;


/* Formatando strings */
/* concatenando */
select cargo ||' - '|| departamento
from funcionarios;

/* TIRANDO CARACTERES VAZIOS*/
SELECT LENGTH('    OLA      ');
SELECT LENGTH(TRIM('    OLA      '));
 

SELECT NOME,CARGO,
CASE 
	WHEN cargo LIKE '%Assistant%' THEN 'é assistente'
	else
	'Não é'
end
from funcionarios;

select nome, (cargo like '%Assistant') as Assistente
from funcionarios;

