/* MODIFICANDO ESTRUTURAS DE TABLEAS */

CREATE TABLE TABELA(
	COLUNA1 VARCHAR(30),
	COLUNA2 VARCHAR(30),
	COLUNA3 VARCHAR(30)
);

/* ALTERANDO UMA COLUNA COMO PL */

ALTER TABLE TABELA
ADD PRIMARY KEY (COLUNA1);


/* ADD COLUANS */
ALTER TABLE TABLEA 
ADD COLUNA  VARCHAR(10));


ALTER TABLE TABELA 
ADD COLUNA100 INT;

ALTER TABLE TABELA
ADD COLUMN COLUNA5 VARCHAR(30) NOT NULL
AFTER COLUNA100;

/* MOFICICANDO A COLUNA (TIPO)*/

/* VOCE SO CONSEGUE ALTERAR OS DADOS SE ELAS SE FALAM  INT --> VARCHAR NAO PODE */

/* VOCE SO CONSEGUE FAZER ESSE TIPO DE ALTERAÇÃO SE A TABELA ESTIVER VAZIA */

ALTER TABLE TABELA
 MODIFY COLUNA2 DATE NOT NULL;

 --RENOMEANDO O NOME DA TABELA
ALTER TABLE TABELA 
RENAME PESSOA;

CREATE TABLE TIME(
	IDTIME INT PRIMARY KEY AUTO_INCREMENT,
	TIME VARCHAR(30),
	ID_PESSOA VARCHAR(30)
);

/* ALTERANDO UMA COLUN APARA FOREIGN KEY*/

ALTER TABLE TIME 
ADD FOREIGN KEY (ID_PESSOA)
REFERENCES PESSOA(COLUNA1)
 
 /* VERIFICANDO AS CHAVES */

SHOW CREATE TABLE TIME

CREATE TABLE JOGADOR(
	IDJOGADOR INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(50)
);

CREATE TABLE TIMES(
	IDTIME INT PRIMARY KEY AUTO_INCREMENT,
	NOMETIME  VARCHAR(30),
	ID_JOGADOR INT,
	FOREIGN KEY (ID_JOGADOR)
	REFERENCES JOGADOR(IDJOGADOR)
); 

INSERT INTO JOGADOR VALUES(NULL,'GUERRERO');
INSERT INTO TIMES VALUES(NULL,'FLAMENGO',1);

/* A35 - ORGANIZANDO CHAVES
 */

SHOW TABLES;

DROP TABLE ENDERECO;
DROP TABLE TELEFONE;
DROP TABLE CLIENTE;

CREATE TABLE CLIENTE(
	IDCLIENTE INT,
	NOME VARCHAR(30) NOT NULL
);

CREATE TABLE TELEFONE(
	IDTELEFONE INT,
	TIPO CHAR(3) NOT NULL,
	NUMERO VARCHAR(10) NOT NULL,
	ID_CLIENTE INT
);

ALTER TABLE CLIENTE ADD CONSTRAINT PK_CLIENTE
PRIMARY KEY (IDCLIENTE);

ALTER TABLE TELEFONE ADD CONSTRAINT FK_CLINETE_TELEFONE
FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(IDCLIENTE);